import type { Pool, StrategyRecommendation, Transaction, Portfolio } from "@shared/schema";

export const mockPools: Pool[] = [
  {
    id: "1",
    protocol: "raydium",
    chain: "solana",
    name: "SOL/USDC",
    tokenA: "SOL",
    tokenB: "USDC",
    apr: 24.5,
    tvl: 12500000,
    volume24h: 3200000,
    fees24h: 9600,
    myLiquidity: 5000,
  },
  {
    id: "2",
    protocol: "raydium",
    chain: "solana",
    name: "RAY/SOL",
    tokenA: "RAY",
    tokenB: "SOL",
    apr: 42.3,
    tvl: 8900000,
    volume24h: 1800000,
    fees24h: 5400,
    myLiquidity: 0,
  },
  {
    id: "3",
    protocol: "cetus",
    chain: "sui",
    name: "SUI/USDC",
    tokenA: "SUI",
    tokenB: "USDC",
    apr: 18.7,
    tvl: 9200000,
    volume24h: 2100000,
    fees24h: 6300,
    myLiquidity: 3200,
  },
  {
    id: "4",
    protocol: "cetus",
    chain: "sui",
    name: "CETUS/SUI",
    tokenA: "CETUS",
    tokenB: "SUI",
    apr: 56.2,
    tvl: 4300000,
    volume24h: 980000,
    fees24h: 2940,
    myLiquidity: 0,
  },
  {
    id: "5",
    protocol: "momentum",
    chain: "sui",
    name: "SUI/USDT",
    tokenA: "SUI",
    tokenB: "USDT",
    apr: 21.8,
    tvl: 6700000,
    volume24h: 1600000,
    fees24h: 4800,
    myLiquidity: 1800,
  },
  {
    id: "6",
    protocol: "raydium",
    chain: "solana",
    name: "BONK/SOL",
    tokenA: "BONK",
    tokenB: "SOL",
    apr: 68.9,
    tvl: 3100000,
    volume24h: 1200000,
    fees24h: 3600,
    myLiquidity: 0,
  },
];

export const mockRecommendations: StrategyRecommendation[] = [
  {
    id: "r1",
    poolId: "2",
    title: "High APR Opportunity: RAY/SOL",
    description: "AI detected favorable market conditions for RAY/SOL pool with low impermanent loss risk",
    confidence: 0.87,
    expectedApr: 42.3,
    estimatedIL: 2.3,
    reason: "Strong upward correlation between RAY and SOL reduces IL risk while maintaining high yield",
    suggestedAmount: 2500,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "r2",
    poolId: "4",
    title: "Optimal Entry Point: CETUS/SUI",
    description: "Price volatility has stabilized, ideal time to enter this high-yield pool",
    confidence: 0.92,
    expectedApr: 56.2,
    estimatedIL: 4.1,
    reason: "Recent volatility decrease combined with high trading volume suggests sustainable APR",
    suggestedAmount: 3000,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "r3",
    poolId: "3",
    title: "Rebalance Alert: SUI/USDC",
    description: "Consider increasing position size based on improved market conditions",
    confidence: 0.78,
    expectedApr: 18.7,
    estimatedIL: 1.2,
    reason: "Stable correlation with low IL risk makes this ideal for risk-averse strategy",
    suggestedAmount: 1500,
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "tx1",
    type: "add_liquidity",
    pool: "SOL/USDC",
    amount: 5000,
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    status: "success",
    txHash: "5KJp8NQ9Xr2mP3dF7Vc8aB4nE6tY9qW1",
  },
  {
    id: "tx2",
    type: "add_liquidity",
    pool: "SUI/USDC",
    amount: 3200,
    timestamp: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    status: "success",
    txHash: "8NmQ2Tp9Kr5Lp8Df3Vc2aH6nR4tX7qP9",
  },
  {
    id: "tx3",
    type: "claim_rewards",
    pool: "SOL/USDC",
    amount: 125.5,
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: "success",
    txHash: "2QrL5Jp8Nt3Mp7Kf9Hc4aB2nD6vY1qX3",
  },
  {
    id: "tx4",
    type: "add_liquidity",
    pool: "SUI/USDT",
    amount: 1800,
    timestamp: new Date(Date.now() - 168 * 60 * 60 * 1000).toISOString(),
    status: "success",
    txHash: "7PmK3Nt8Qr2Lp5Df6Vc9aJ4nE8tW2qY1",
  },
];

export const mockPortfolio: Portfolio = {
  totalValue: 10125.5,
  totalRewards: 342.8,
  activePositions: 3,
  averageApr: 21.7,
};
